version: '3.6'

services:
  deadline:
    image: 80.86.165.30:5000/privacy:prod
    environment:
      VIRTUAL_HOST: ${SUBDOMAIN}.apps.andrena.de
      LETSENCRYPT_HOST: ${SUBDOMAIN}.apps.andrena.de
      LETSENCRYPT_EMAIL: conrad.thukral@andrena.de
      BUILD_NUMBER: ${BUILD}
    networks:
      - autopublish
      - default


networks:
  autopublish:
    external: true
    name: infrastructure_autopublish
